export const GETCASESTUDYDETAIL = "GETCASESTUDYDETAIL";
export const GETQUICKLINKDETAIL = "GETQUICKLINKDETAIL";
export const GETSEARCHDATA = "GETSEARCHDATA";
export const GETFILTERS = "GETFILTERS";
export const GETSEARCHITEMPREVIEWDATA = "GETSEARCHITEMPREVIEWDATA";
export const GETSEARCHVALUE = "GETSEARCHVALUE";

// Theme Reducer
export const UPDATETHEME = "UPDATETHEME";
export const UPDATEFULLSCREENSTATUS = "UPDATEFULLSCREENSTATUS";
export const SETMENUCOLLAPSED = "SETMENUCOLLAPSED";

//Login Reducer
export const AUTHENTICATEUSER = "AUTHENTICATEUSER";

//Error Reducer
export const SETERROR = "SETERROR";

//Source Reducer
export const CREATESOURCE="CREATESOURCE"
export const GETSOURCES = "GETSOURCES";
export const DELETESOURCE = "DELETESOURCE";
export const GETSOURCEDETAIL = "GETSOURCEDETAIL";


