export const GETCASESTUDYDETAIL = "GETCASESTUDYDETAIL";
export const GETQUICKLINKDETAIL = "GETQUICKLINKDETAIL";
export const GETSEARCHDATA = "GETSEARCHDATA";
export const GETFILTERS = "GETFILTERS";
export const GETSEARCHITEMPREVIEWDATA = "GETSEARCHITEMPREVIEWDATA";
export const GETSEARCHVALUE = "GETSEARCHVALUE";
